# Generated by Django 5.0.3 on 2024-04-03 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('village_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('complaints', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('housenumber', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100)),
                ('mobilenumber', models.CharField(max_length=100, null=True)),
                ('wardnumber', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=8)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petname', models.CharField(max_length=100)),
                ('pettype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='village_admin.petcategory')),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='village_website.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('occupation', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('bloodgroup', models.CharField(max_length=10)),
                ('userinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='village_website.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=100)),
                ('vehicle_img', models.ImageField(upload_to='vehicles/')),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='village_website.userinfo')),
                ('vehicle_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='village_admin.vehiclecategory')),
            ],
        ),
    ]
