# Generated by Django 5.0.3 on 2024-04-07 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('img', models.ImageField(upload_to='posts/')),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='village_website.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('mobilenumber', models.IntegerField(max_length=100)),
                ('userinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='village_website.userinfo')),
            ],
        ),
    ]
