# Generated by Django 5.0.3 on 2024-05-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village_website', '0006_alter_userinfo_mobilenumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='mobilenumber',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
